import { createContext, useContext, useMemo, useState } from 'react'

const translations = {
  en: {
    navHome: 'Home',
    navTreks: 'Treks',
    navAbout: 'About',
    navBlog: 'Blog',
    navGallery: 'Gallery',
    navGuide: 'Guide',
    navContact: 'Contact',
    navAdmin: 'Admin',
    navDashboard: 'Dashboard',
    navBookings: 'My Bookings',
    navMore: 'More',
    navFaq: 'FAQ',
    navPartners: 'Partners',
    navTrust: 'Trust & Safety',
    navCalculator: 'Calculator',
    navSignIn: 'Sign In',
    navRegister: 'Register',
    navLogout: 'Logout',
    navWelcome: 'Welcome',
    homeTagline: 'Himalayan Adventures',
    homeTitle: 'Everest Encounter Treks & Expedition Pvt. Ltd.',
    homeSubtitle:
      'Design your next expedition with curated trek lines, air access options, and expert-guided itineraries across Nepal.',
    homeBook: 'Book a Trek',
    homeView: 'View Packages',
    homeModesTitle: 'Adventure Modes',
    homeModesSubtitle:
      'Choose how you want to reach the mountains and unlock new routes.',
    homeSignatureTitle: 'Signature Treks',
    homeSignatureView: 'View all treks',
    homeServicesTitle: 'Services Built for Remote Expeditions',
    homeServicesSubtitle:
      'Logistics, permits, and altitude planning handled by local experts.',
    homeCertifiedGuides: 'Certified Guides',
    homeSafetyFirst: 'Safety First',
    homeCustomItineraries: 'Custom Itineraries',
    homeSearchPlaceholder: 'Search treks or highlights',
    homeAllRegions: 'All Regions',
    homeExplore: 'Explore',
    homeRoutes: '18+ Routes',
    homeHeroAlt: 'Mountain panorama',
    homeWeatherTitle: 'Weather Watch',
    homeWeatherBody: 'Live season planning for optimal visibility.',
    homeBriefTitle: 'Expedition Brief',
    homeBriefBody: 'Daily altitude checks and permit coordination.',
    homeSeePackages: 'See all packages >',
    homeModeFlights: 'Scenic Flights',
    homeModeHeli: 'Heli Access',
    homeModeParaglide: 'Paragliding',
    homeModeHighAltitude: 'High-Altitude Treks',
    homeModeHint: 'View routes tailored to this adventure mode.',
    homeLoadingTreks: 'Loading treks...',
    homeSignatureBody:
      'Balanced itineraries with acclimatization, cultural immersion, and panoramic ridge walks.',
    homeServicesItem1: 'Dedicated trek leaders and certified guides',
    homeServicesItem2: 'Helicopter evacuation coordination',
    homeServicesItem3: 'Porter support and sustainable trail practices',
    homeServicesItem4: 'Custom itineraries and acclimatization plans',
    homeTestimonials: 'Testimonials',
    homeTestimonialsSubtitle: 'Traveler feedback from recent expeditions.',
    homeTestimonialsEmpty: 'Be the first to share your expedition experience.',
    homeTestimonialsNote:
      'Video testimonials are shared with confirmed travelers upon request.',
    homePrepItem1: 'TIMS card & Sagarmatha NP permit support',
    homePrepItem2: 'Altitude awareness and emergency planning',
    homePrepItem3: 'Equipment checklist and packing templates',
    homeGalleryTitle: 'Gallery Highlights',
    homeGalleryView: 'View gallery >',
    homePrepTitle: 'Pre-departure Preparation',
    homePrepSubtitle:
      'Fitness advice, permits, and safety briefings ready for every trek.',
    homeOpenGuide: 'Open guide',
    trekListTitle: 'Trek Catalog',
    trekListSubtitle:
      'Filter by region, difficulty, and price band to find your perfect route.',
    trekSearch: 'Search treks',
    trekRegion: 'All Regions',
    trekDifficulty: 'Difficulty',
    trekSeason: 'Best season',
    trekDuration: 'Duration',
    trekPrice: 'Price Band',
    trekApply: 'Apply Filters',
    trekViewDetails: 'View Details',
    trekLoadError: 'Unable to load treks. Please try again soon.',
    trekEmpty: 'No treks match the selected filters.',
    trekRegionFallback: 'Himalayan region',
    trekDays: 'days',
    trekAltitude: 'Altitude',
    trekSeason_SpringAutumn: 'Spring/Autumn',
    trekCardFallback: 'Remote trails and alpine villages.',
    trekDifficulty_Easy: 'Easy',
    trekDifficulty_Moderate: 'Moderate',
    trekDifficulty_Challenging: 'Challenging',
    trekDifficulty_Extreme: 'Extreme',
    trekSeason_Spring: 'Spring',
    trekSeason_Summer: 'Summer',
    trekSeason_Autumn: 'Autumn',
    trekSeason_Winter: 'Winter',
    trekDuration_Short: 'Short (1-7)',
    trekDuration_Medium: 'Medium (8-14)',
    trekDuration_Long: 'Long (15+)',
    trekPriceBudget: 'Budget',
    trekPriceComfort: 'Comfort',
    trekPricePremium: 'Premium',
    loginTitle: 'Welcome back',
    loginSubtitle: 'Log in to manage bookings and expeditions.',
    loginEmail: 'Email',
    loginPassword: 'Password',
    loginButton: 'Sign In',
    registerTitle: 'Create account',
    registerSubtitle: 'Start planning your next Himalayan expedition.',
    registerName: 'Full name',
    registerEmail: 'Email',
    registerPassword: 'Password',
    registerConfirm: 'Confirm password',
    registerButton: 'Register',
    myBookingsTitle: 'My Bookings',
    myBookingsSubtitle: 'Track payment status and upcoming departure dates.',
    payNow: 'Pay now',
    paymentTitle: 'Payment',
    paymentSubtitle: 'Complete your payment to confirm the booking.',
    paymentDetails: 'Payment Details',
    paymentSuccessTitle: 'Payment Successful',
    paymentCancelTitle: 'Payment Cancelled',
    paymentGoBookings: 'Go to My Bookings',
    paymentTryAgain: 'Try Again',
    paymentBack: 'Back to bookings',
    paymentNotFound: 'Booking not found.',
    paymentLoading: 'Loading booking...',
    paymentStatus: 'Status',
    paymentPeople: 'People',
    paymentPricePerPerson: 'Price per person',
    paymentTotal: 'Total',
    paymentPayNow: 'Pay Now',
    paymentProcessing: 'Processing...',
    stepBooking: 'Booking',
    stepPayment: 'Payment',
    stepConfirmation: 'Confirmation',
    bookingLoading: 'Loading bookings...',
    bookingLoadError: 'Unable to load bookings right now.',
    bookingEmpty: 'You have no bookings yet.',
    bookingStartDate: 'Start date',
    bookingAmount: 'Amount',
    bookingPayment: 'Payment',
    bookingInvoice: 'Download invoice',
    bookingPending: 'Pending',
    authCreating: 'Creating account...',
    authExisting: 'Already have an account?',
    authSignInLink: 'Sign in',
    authProcessing: 'Signing in...',
    authNoAccount: "Don't have an account?",
    authRegisterLink: 'Create one',
    authWelcomeTraveler: 'Traveler',
    aboutTitle: 'About Us',
    aboutIntro1:
      'Everest Encounter Treks and Expedition Pvt. Ltd is a Kathmandu-based team of certified mountain guides and cultural storytellers. We craft journeys that balance altitude safety, environmental care, and immersive local encounters.',
    aboutIntro2:
      'Our operations team monitors weather and trail conditions daily, ensuring every expedition is tailored to the season. From the first briefing to the final celebration dinner, we focus on details that keep trekkers confident on the trail.',
    aboutStatYears: 'Years guiding',
    aboutStatTrekkers: 'Happy trekkers',
    aboutStatRoutes: 'Signature routes',
    aboutTeamTitle: 'Meet the Team',
    aboutRoleLeadGuide: 'Lead Guide',
    aboutRoleLeadGuideBody:
      'IFMGA-trained guide specializing in Everest and Annapurna routes.',
    aboutRoleOps: 'Operations',
    aboutRoleOpsBody:
      'Logistics coordinator overseeing permits, lodges, and safety briefings.',
    aboutRoleCulture: 'Cultural Liaison',
    aboutRoleCultureBody:
      'Local heritage expert bringing community stories into every trek.',
    aboutRoleSafety: 'Safety Officer',
    aboutRoleSafetyBody:
      'Leads emergency preparedness and daily altitude monitoring.',
    aboutPromiseTitle: 'Our Promise',
    aboutPromiseItem1: 'Certified guides and altitude-first safety protocols.',
    aboutPromiseItem2: 'Ethical partnerships with local lodges and porters.',
    aboutPromiseItem3: 'Small groups to protect trails and cultures.',
    aboutPromiseItem4: 'On-ground logistics support 24/7.',
    aboutPromiseNote:
      'Responsible travel is at the core of every itinerary we design.',
    blogTitle: 'Trail Journal',
    contactTitle: 'Contact Us',
    faqTitle: 'Frequently Asked Questions',
    guideTitle: 'Pre-departure Guide & Preparation',
    partnersTitle: 'Partners & Affiliates',
    trustTitle: 'Trust & Safety',
    calculatorTitle: 'Trip Cost Calculator',
  },
  uk: {
    navHome: 'Home',
    navTreks: 'Treks',
    navAbout: 'About',
    navBlog: 'Blog',
    navGallery: 'Gallery',
    navGuide: 'Guide',
    navContact: 'Contact',
    navAdmin: 'Admin',
    navDashboard: 'Dashboard',
    navBookings: 'My Bookings',
    homeTagline: 'Himalayan Adventures',
    homeTitle: 'Everest Encounter Treks & Expedition Pvt. Ltd.',
    homeSubtitle:
      'Design your next expedition with curated trek lines, air access options, and expert-guided itineraries across Nepal.',
    homeBook: 'Book a Trek',
    homeView: 'View Packages',
    homeModesTitle: 'Adventure Modes',
    homeModesSubtitle:
      'Choose how you want to reach the mountains and unlock new routes.',
    homeSignatureTitle: 'Signature Treks',
    homeSignatureView: 'View all treks',
    homeServicesTitle: 'Services Built for Remote Expeditions',
    homeServicesSubtitle:
      'Logistics, permits, and altitude planning handled by local experts.',
    homeCertifiedGuides: 'Certified Guides',
    homeSafetyFirst: 'Safety First',
    homeCustomItineraries: 'Custom Itineraries',
    homeSearchPlaceholder: 'Search treks or highlights',
    homeAllRegions: 'All Regions',
    homeExplore: 'Explore',
    homeRoutes: '18+ Routes',
    homeHeroAlt: 'Mountain panorama',
    homeWeatherTitle: 'Weather Watch',
    homeWeatherBody: 'Live season planning for optimal visibility.',
    homeBriefTitle: 'Expedition Brief',
    homeBriefBody: 'Daily altitude checks and permit coordination.',
    homeSeePackages: 'See all packages >',
    homeModeFlights: 'Scenic Flights',
    homeModeHeli: 'Heli Access',
    homeModeParaglide: 'Paragliding',
    homeModeHighAltitude: 'High-Altitude Treks',
    homeModeHint: 'View routes tailored to this adventure mode.',
    homeLoadingTreks: 'Loading treks...',
    homeSignatureBody:
      'Balanced itineraries with acclimatization, cultural immersion, and panoramic ridge walks.',
    homeServicesItem1: 'Dedicated trek leaders and certified guides',
    homeServicesItem2: 'Helicopter evacuation coordination',
    homeServicesItem3: 'Porter support and sustainable trail practices',
    homeServicesItem4: 'Custom itineraries and acclimatization plans',
    homeTestimonials: 'Testimonials',
    homeTestimonialsSubtitle: 'Traveler feedback from recent expeditions.',
    homeTestimonialsEmpty: 'Be the first to share your expedition experience.',
    homeTestimonialsNote:
      'Video testimonials are shared with confirmed travelers upon request.',
    homePrepItem1: 'TIMS card & Sagarmatha NP permit support',
    homePrepItem2: 'Altitude awareness and emergency planning',
    homePrepItem3: 'Equipment checklist and packing templates',
    homeGalleryTitle: 'Gallery Highlights',
    homeGalleryView: 'View gallery >',
    homePrepTitle: 'Pre-departure Preparation',
    homePrepSubtitle:
      'Fitness advice, permits, and safety briefings ready for every trek.',
    homeOpenGuide: 'Open guide',
    trekListTitle: 'Trek Catalogue',
    trekListSubtitle:
      'Filter by region, difficulty, and price band to find your perfect route.',
    trekSearch: 'Search treks',
    trekRegion: 'All Regions',
    trekDifficulty: 'Difficulty',
    trekSeason: 'Best season',
    trekDuration: 'Duration',
    trekPrice: 'Price Band',
    trekApply: 'Apply Filters',
    trekViewDetails: 'View Details',
    trekLoadError: 'Unable to load treks. Please try again soon.',
    trekEmpty: 'No treks match the selected filters.',
    trekRegionFallback: 'Himalayan region',
    trekDays: 'days',
    trekAltitude: 'Altitude',
    trekSeason_SpringAutumn: 'Spring/Autumn',
    trekCardFallback: 'Remote trails and alpine villages.',
    trekDifficulty_Easy: 'Easy',
    trekDifficulty_Moderate: 'Moderate',
    trekDifficulty_Challenging: 'Challenging',
    trekDifficulty_Extreme: 'Extreme',
    trekSeason_Spring: 'Spring',
    trekSeason_Summer: 'Summer',
    trekSeason_Autumn: 'Autumn',
    trekSeason_Winter: 'Winter',
    trekDuration_Short: 'Short (1-7)',
    trekDuration_Medium: 'Medium (8-14)',
    trekDuration_Long: 'Long (15+)',
    trekPriceBudget: 'Budget',
    trekPriceComfort: 'Comfort',
    trekPricePremium: 'Premium',
    loginTitle: 'Welcome back',
    loginSubtitle: 'Log in to manage bookings and expeditions.',
    loginEmail: 'Email',
    loginPassword: 'Password',
    loginButton: 'Sign In',
    registerTitle: 'Create account',
    registerSubtitle: 'Start planning your next Himalayan expedition.',
    registerName: 'Full name',
    registerEmail: 'Email',
    registerPassword: 'Password',
    registerConfirm: 'Confirm password',
    registerButton: 'Register',
    myBookingsTitle: 'My Bookings',
    myBookingsSubtitle: 'Track payment status and upcoming departure dates.',
    payNow: 'Pay now',
    paymentTitle: 'Payment',
    paymentSubtitle: 'Complete your payment to confirm the booking.',
    paymentDetails: 'Payment Details',
    paymentSuccessTitle: 'Payment Successful',
    paymentCancelTitle: 'Payment Cancelled',
    paymentGoBookings: 'Go to My Bookings',
    paymentTryAgain: 'Try Again',
    aboutTitle: 'About Us',
    aboutIntro1:
      'Everest Encounter Treks and Expedition Pvt. Ltd is a Kathmandu-based team of certified mountain guides and cultural storytellers. We craft journeys that balance altitude safety, environmental care, and immersive local encounters.',
    aboutIntro2:
      'Our operations team monitors weather and trail conditions daily, ensuring every expedition is tailored to the season. From the first briefing to the final celebration dinner, we focus on details that keep trekkers confident on the trail.',
    aboutStatYears: 'Years guiding',
    aboutStatTrekkers: 'Happy trekkers',
    aboutStatRoutes: 'Signature routes',
    aboutTeamTitle: 'Meet the Team',
    aboutRoleLeadGuide: 'Lead Guide',
    aboutRoleLeadGuideBody:
      'IFMGA-trained guide specializing in Everest and Annapurna routes.',
    aboutRoleOps: 'Operations',
    aboutRoleOpsBody:
      'Logistics coordinator overseeing permits, lodges, and safety briefings.',
    aboutRoleCulture: 'Cultural Liaison',
    aboutRoleCultureBody:
      'Local heritage expert bringing community stories into every trek.',
    aboutRoleSafety: 'Safety Officer',
    aboutRoleSafetyBody:
      'Leads emergency preparedness and daily altitude monitoring.',
    aboutPromiseTitle: 'Our Promise',
    aboutPromiseItem1: 'Certified guides and altitude-first safety protocols.',
    aboutPromiseItem2: 'Ethical partnerships with local lodges and porters.',
    aboutPromiseItem3: 'Small groups to protect trails and cultures.',
    aboutPromiseItem4: 'On-ground logistics support 24/7.',
    aboutPromiseNote:
      'Responsible travel is at the core of every itinerary we design.',
    blogTitle: 'Trail Journal',
    contactTitle: 'Contact Us',
    faqTitle: 'Frequently Asked Questions',
    guideTitle: 'Pre-departure Guide & Preparation',
    partnersTitle: 'Partners & Affiliates',
    trustTitle: 'Trust & Safety',
    calculatorTitle: 'Trip Cost Calculator',
  },
  es: {
    navHome: 'Inicio',
    navTreks: 'Trekking',
    navAbout: 'Nosotros',
    navBlog: 'Blog',
    navGallery: 'Galeria',
    navGuide: 'Guia',
    navContact: 'Contacto',
    navAdmin: 'Admin',
    navDashboard: 'Panel',
    navBookings: 'Mis Reservas',
    homeTagline: 'Aventuras Himalayas',
    homeTitle: 'Everest Encounter Treks & Expedition Pvt. Ltd.',
    homeSubtitle:
      'Planifica tu expedición con rutas seleccionadas y guías expertos en Nepal.',
    homeBook: 'Reservar Trek',
    homeView: 'Ver Paquetes',
    homeModesTitle: 'Modos de Aventura',
    homeModesSubtitle:
      'Elige cómo llegar a las montañas y descubre nuevas rutas.',
    homeSignatureTitle: 'Treks Destacados',
    homeSignatureView: 'Ver todos los treks',
    homeServicesTitle: 'Servicios para Expediciones Remotas',
    homeServicesSubtitle:
      'Logística, permisos y planificación de altura a cargo de expertos.',
    homePrepTitle: 'Preparación Previa',
    homePrepSubtitle:
      'Consejos de fitness, permisos y seguridad para cada trek.',
    homeOpenGuide: 'Abrir guía',
    trekListTitle: 'Catálogo de Treks',
    trekListSubtitle:
      'Filtra por región, dificultad y precio para encontrar tu ruta.',
    trekSearch: 'Buscar treks',
    trekRegion: 'Todas las regiones',
    trekDifficulty: 'Dificultad',
    trekSeason: 'Mejor temporada',
    trekDuration: 'Duración',
    trekPrice: 'Precio',
    trekApply: 'Aplicar filtros',
    trekViewDetails: 'Ver detalles',
    loginTitle: 'Bienvenido',
    loginSubtitle: 'Inicia sesión para gestionar reservas.',
    loginEmail: 'Correo',
    loginPassword: 'Contraseña',
    loginButton: 'Entrar',
    registerTitle: 'Crear cuenta',
    registerSubtitle: 'Planifica tu próxima expedición.',
    registerName: 'Nombre completo',
    registerEmail: 'Correo',
    registerPassword: 'Contraseña',
    registerConfirm: 'Confirmar contraseña',
    registerButton: 'Registrar',
    myBookingsTitle: 'Mis reservas',
    myBookingsSubtitle: 'Estado de pagos y próximas salidas.',
    payNow: 'Pagar ahora',
    paymentTitle: 'Pago',
    paymentSubtitle: 'Completa el pago para confirmar.',
    paymentDetails: 'Detalles de pago',
    paymentSuccessTitle: 'Pago exitoso',
    paymentCancelTitle: 'Pago cancelado',
    paymentGoBookings: 'Ir a mis reservas',
    paymentTryAgain: 'Intentar de nuevo',
    aboutTitle: 'Sobre nosotros',
    blogTitle: 'Diario de Ruta',
    contactTitle: 'Contáctanos',
    faqTitle: 'Preguntas frecuentes',
    guideTitle: 'Guía de preparación',
    partnersTitle: 'Socios',
    trustTitle: 'Confianza y seguridad',
    calculatorTitle: 'Calculadora de costos',
  },
  fr: {
    navHome: 'Accueil',
    navTreks: 'Treks',
    navAbout: 'A propos',
    navBlog: 'Blog',
    navGallery: 'Galerie',
    navGuide: 'Guide',
    navContact: 'Contact',
    navAdmin: 'Admin',
    navDashboard: 'Tableau',
    navBookings: 'Mes réservations',
    homeTagline: 'Aventures Himalayennes',
    homeTitle: 'Everest Encounter Treks & Expedition Pvt. Ltd.',
    homeSubtitle:
      'Planifiez votre expédition avec des itinéraires sélectionnés au Népal.',
    homeBook: 'Réserver un trek',
    homeView: 'Voir les offres',
    homeModesTitle: 'Modes d’aventure',
    homeModesSubtitle:
      'Choisissez votre accès aux montagnes et de nouvelles routes.',
    homeSignatureTitle: 'Treks signatures',
    homeSignatureView: 'Voir tous les treks',
    homeServicesTitle: 'Services pour expéditions',
    homeServicesSubtitle:
      'Logistique, permis et planification altitude par des experts.',
    homePrepTitle: 'Préparation',
    homePrepSubtitle:
      'Conseils fitness, permis et sécurité pour chaque trek.',
    homeOpenGuide: 'Ouvrir le guide',
    trekListTitle: 'Catalogue de treks',
    trekListSubtitle:
      'Filtrez par région, difficulté et prix pour votre itinéraire.',
    trekSearch: 'Rechercher',
    trekRegion: 'Toutes les régions',
    trekDifficulty: 'Difficulté',
    trekSeason: 'Meilleure saison',
    trekDuration: 'Durée',
    trekPrice: 'Prix',
    trekApply: 'Appliquer',
    trekViewDetails: 'Voir détails',
    loginTitle: 'Bon retour',
    loginSubtitle: 'Connectez-vous pour gérer vos réservations.',
    loginEmail: 'Email',
    loginPassword: 'Mot de passe',
    loginButton: 'Se connecter',
    registerTitle: 'Créer un compte',
    registerSubtitle: 'Préparez votre prochaine expédition.',
    registerName: 'Nom complet',
    registerEmail: 'Email',
    registerPassword: 'Mot de passe',
    registerConfirm: 'Confirmer',
    registerButton: 'Créer',
    myBookingsTitle: 'Mes réservations',
    myBookingsSubtitle: 'Suivi des paiements et départs.',
    payNow: 'Payer',
    paymentTitle: 'Paiement',
    paymentSubtitle: 'Finalisez pour confirmer.',
    paymentDetails: 'Détails du paiement',
    paymentSuccessTitle: 'Paiement réussi',
    paymentCancelTitle: 'Paiement annulé',
    paymentGoBookings: 'Voir mes réservations',
    paymentTryAgain: 'Réessayer',
    aboutTitle: 'À propos',
    blogTitle: 'Journal',
    contactTitle: 'Contact',
    faqTitle: 'FAQ',
    guideTitle: 'Guide de préparation',
    partnersTitle: 'Partenaires',
    trustTitle: 'Confiance & Sécurité',
    calculatorTitle: 'Calculateur de coût',
  },
  zh: {
    navHome: 'Shouye',
    navTreks: 'Tujing',
    navAbout: 'Guanyu',
    navBlog: 'Boke',
    navGallery: 'Huaxia',
    navGuide: 'Zhinan',
    navContact: 'Lianxi',
    navAdmin: 'Guanli',
    navDashboard: 'Kongzhi',
    navBookings: 'Wode Yuding',
    homeTagline: 'Ximalaya Maoxian',
    homeTitle: 'Everest Encounter Treks & Expedition Pvt. Ltd.',
    homeSubtitle: 'Zai Niboer gui hua ni de xiahuo luxian.',
    homeBook: 'Yuding Tujing',
    homeView: 'Chakan Taocan',
    homeModesTitle: 'Maoxian Fangshi',
    homeModesSubtitle: 'Xuanze jinru shanqu de fangshi.',
    homeSignatureTitle: 'Jingxuan Tujing',
    homeSignatureView: 'Chakan quanbu',
    homeServicesTitle: 'Yuancheng Dengshan Fuwu',
    homeServicesSubtitle: 'Permit, logistics he altitude plan.',
    homePrepTitle: 'Chufa Qian Zhunbei',
    homePrepSubtitle: 'Tixun, permit he anquan zhidao.',
    homeOpenGuide: 'Dakai Zhidao',
    trekListTitle: 'Tujing Mululu',
    trekListSubtitle: 'An diqu, nandux, jiage shaixuan.',
    trekSearch: 'Sousuo',
    trekRegion: 'Suoyou diqu',
    trekDifficulty: 'Nandu',
    trekSeason: 'Zuihao jiejie',
    trekDuration: 'Shichang',
    trekPrice: 'Jiage',
    trekApply: 'Shaixuan',
    trekViewDetails: 'Chakan',
    loginTitle: 'Huanying huilai',
    loginSubtitle: 'Denglu guanli yuding.',
    loginEmail: 'Youxiang',
    loginPassword: 'Mima',
    loginButton: 'Denglu',
    registerTitle: 'Chuangjian zhanghao',
    registerSubtitle: 'Kaishi ni de xiahuo lücheng.',
    registerName: 'Quanming',
    registerEmail: 'Youxiang',
    registerPassword: 'Mima',
    registerConfirm: 'Queren mima',
    registerButton: 'Zhuce',
    myBookingsTitle: 'Wode Yuding',
    myBookingsSubtitle: 'Zhifu zhuangtai he chufa riqi.',
    payNow: 'Liji zhifu',
    paymentTitle: 'Zhifu',
    paymentSubtitle: 'Wancheng zhifu yi queren.',
    paymentDetails: 'Zhifu xiangqing',
    paymentSuccessTitle: 'Zhifu chenggong',
    paymentCancelTitle: 'Zhifu quxiao',
    paymentGoBookings: 'Chakan yuding',
    paymentTryAgain: 'Zaishi',
    aboutTitle: 'Guanyu women',
    blogTitle: 'Luyou Riji',
    contactTitle: 'Lianxi women',
    faqTitle: 'Changjian wenti',
    guideTitle: 'Chufa zhidao',
    partnersTitle: 'Hezuo huoban',
    trustTitle: 'Xinyu yu anquan',
    calculatorTitle: 'Feiyong jisuan',
  },
  hi: {
    navHome: 'होम',
    navTreks: 'ट्रेक्स',
    navAbout: 'हमारे बारे में',
    navBlog: 'ब्लॉग',
    navGallery: 'गैलरी',
    navGuide: 'गाइड',
    navContact: 'संपर्क',
    navAdmin: 'एडमिन',
    navDashboard: 'डैशबोर्ड',
    navBookings: 'मेरी बुकिंग्स',
    homeTagline: 'हिमालयी रोमांच',
    homeTitle: 'एवरेस्ट एन्काउंटर ट्रेक्स एंड एक्सपेडिशन',
    homeSubtitle:
      'नेपाल में विशेषज्ञ गाइड्स के साथ अपने अगले अभियान की योजना बनाएं।',
    homeBook: 'ट्रेक बुक करें',
    homeView: 'पैकेज देखें',
    homeModesTitle: 'एडवेंचर मोड्स',
    homeModesSubtitle: 'पहाड़ों तक पहुँचने के विकल्प चुनें।',
    homeSignatureTitle: 'सिग्नेचर ट्रेक्स',
    homeSignatureView: 'सभी ट्रेक्स देखें',
    homeServicesTitle: 'दूरस्थ अभियानों की सेवाएँ',
    homeServicesSubtitle: 'लॉजिस्टिक्स, परमिट और ऊँचाई योजना।',
    homePrepTitle: 'यात्रा से पहले तैयारी',
    homePrepSubtitle: 'फिटनेस, परमिट और सुरक्षा गाइड।',
    homeOpenGuide: 'गाइड खोलें',
    trekListTitle: 'ट्रेक कैटलॉग',
    trekListSubtitle: 'क्षेत्र, कठिनाई और कीमत के अनुसार फ़िल्टर करें।',
    trekSearch: 'ट्रेक खोजें',
    trekRegion: 'सभी क्षेत्र',
    trekDifficulty: 'कठिनाई',
    trekSeason: 'सर्वोत्तम मौसम',
    trekDuration: 'अवधि',
    trekPrice: 'कीमत',
    trekApply: 'फ़िल्टर लागू करें',
    trekViewDetails: 'विवरण देखें',
    loginTitle: 'वापसी पर स्वागत है',
    loginSubtitle: 'बुकिंग प्रबंधित करने के लिए लॉगिन करें।',
    loginEmail: 'ईमेल',
    loginPassword: 'पासवर्ड',
    loginButton: 'साइन इन',
    registerTitle: 'खाता बनाएं',
    registerSubtitle: 'अपना अगला अभियान प्लान करें।',
    registerName: 'पूरा नाम',
    registerEmail: 'ईमेल',
    registerPassword: 'पासवर्ड',
    registerConfirm: 'पासवर्ड पुष्टि',
    registerButton: 'रजिस्टर',
    myBookingsTitle: 'मेरी बुकिंग्स',
    myBookingsSubtitle: 'भुगतान स्थिति और प्रस्थान तिथि।',
    payNow: 'अभी भुगतान करें',
    paymentTitle: 'भुगतान',
    paymentSubtitle: 'बुकिंग पुष्टि के लिए भुगतान करें।',
    paymentDetails: 'भुगतान विवरण',
    paymentSuccessTitle: 'भुगतान सफल',
    paymentCancelTitle: 'भुगतान रद्द',
    paymentGoBookings: 'मेरी बुकिंग्स देखें',
    paymentTryAgain: 'फिर से प्रयास करें',
    aboutTitle: 'हमारे बारे में',
    blogTitle: 'ट्रेल जर्नल',
    contactTitle: 'संपर्क करें',
    faqTitle: 'अक्सर पूछे प्रश्न',
    guideTitle: 'तैयारी गाइड',
    partnersTitle: 'साझेदार',
    trustTitle: 'विश्वास और सुरक्षा',
    calculatorTitle: 'यात्रा लागत कैलकुलेटर',
  },
  ne: {
    navHome: 'होम',
    navTreks: 'ट्रेक्स',
    navAbout: 'हाम्रो बारे',
    navBlog: 'ब्लग',
    navGallery: 'ग्यालेरी',
    navGuide: 'गाइड',
    navContact: 'सम्पर्क',
    navAdmin: 'एडमिन',
    navDashboard: 'ड्यासबोर्ड',
    navBookings: 'मेरो बुकिङ',
    homeTagline: 'हिमालय रोमाञ्च',
    homeTitle: 'एभरेस्ट एनकाउण्टर ट्रेक्स एण्ड एक्सपेडिसन',
    homeSubtitle:
      'नेपालमा विशेषज्ञ गाइडका साथ अर्को अभियान योजना बनाउनुहोस्।',
    homeBook: 'ट्रेक बुक गर्नुहोस्',
    homeView: 'प्याकेज हेर्नुहोस्',
    homeModesTitle: 'एड्भेन्चर मोड्स',
    homeModesSubtitle: 'पहाड पुग्ने विकल्प छान्नुहोस्।',
    homeSignatureTitle: 'सिग्नेचर ट्रेक्स',
    homeSignatureView: 'सबै ट्रेक्स हेर्नुहोस्',
    homeServicesTitle: 'दूरस्थ अभियानका सेवा',
    homeServicesSubtitle: 'लजिस्टिक्स, परमिट र उचाइ योजना।',
    homePrepTitle: 'पूर्व तयारी',
    homePrepSubtitle: 'फिटनेस, परमिट र सुरक्षा गाइड।',
    homeOpenGuide: 'गाइड खोल्नुहोस्',
    trekListTitle: 'ट्रेक क्याटलग',
    trekListSubtitle: 'क्षेत्र, कठिनाइ र मूल्य अनुसार फिल्टर गर्नुहोस्।',
    trekSearch: 'ट्रेक खोज्नुहोस्',
    trekRegion: 'सबै क्षेत्र',
    trekDifficulty: 'कठिनाइ',
    trekSeason: 'उत्तम मौसम',
    trekDuration: 'अवधि',
    trekPrice: 'मूल्य',
    trekApply: 'फिल्टर लागू',
    trekViewDetails: 'विवरण हेर्नुहोस्',
    loginTitle: 'फेरि स्वागत छ',
    loginSubtitle: 'बुकिङ व्यवस्थापनका लागि लगइन गर्नुहोस्।',
    loginEmail: 'इमेल',
    loginPassword: 'पासवर्ड',
    loginButton: 'लगइन',
    registerTitle: 'खाता बनाउनुहोस्',
    registerSubtitle: 'अर्को अभियान योजना बनाउनुहोस्।',
    registerName: 'पूरा नाम',
    registerEmail: 'इमेल',
    registerPassword: 'पासवर्ड',
    registerConfirm: 'पासवर्ड पुष्टि',
    registerButton: 'दर्ता',
    myBookingsTitle: 'मेरो बुकिङ',
    myBookingsSubtitle: 'भुक्तानी स्थिति र प्रस्थान मिति।',
    payNow: 'अहिले भुक्तानी',
    paymentTitle: 'भुक्तानी',
    paymentSubtitle: 'बुकिङ पुष्टि गर्न भुक्तानी गर्नुहोस्।',
    paymentDetails: 'भुक्तानी विवरण',
    paymentSuccessTitle: 'भुक्तानी सफल',
    paymentCancelTitle: 'भुक्तानी रद्द',
    paymentGoBookings: 'मेरो बुकिङ हेर्नुहोस्',
    paymentTryAgain: 'फेरि प्रयास',
    aboutTitle: 'हाम्रो बारे',
    blogTitle: 'ट्रेल जर्नल',
    contactTitle: 'सम्पर्क गर्नुहोस्',
    faqTitle: 'बारम्बार सोधिने प्रश्न',
    guideTitle: 'तयारी गाइड',
    partnersTitle: 'साझेदार',
    trustTitle: 'विश्वास र सुरक्षा',
    calculatorTitle: 'यात्रा लागत क्यालकुलेटर',
  },
  ja: {
    navHome: 'ホーム',
    navTreks: 'トレック',
    navAbout: '私たちについて',
    navBlog: 'ブログ',
    navGallery: 'ギャラリー',
    navGuide: 'ガイド',
    navContact: '連絡先',
    navAdmin: '管理',
    navDashboard: 'ダッシュボード',
    navBookings: '予約',
    homeTagline: 'ヒマラヤの冒険',
    homeTitle: 'Everest Encounter Treks & Expedition',
    homeSubtitle: 'ネパールで次の遠征を計画しましょう。',
    homeBook: 'トレック予約',
    homeView: 'パッケージを見る',
    homeModesTitle: '冒険モード',
    homeModesSubtitle: '山へのアクセス方法を選択。',
    homeSignatureTitle: 'おすすめトレック',
    homeSignatureView: 'すべて見る',
    homeServicesTitle: '遠征サポート',
    homeServicesSubtitle: '許可・物流・高度計画。',
    homePrepTitle: '出発前準備',
    homePrepSubtitle: 'フィットネスと安全ガイド。',
    homeOpenGuide: 'ガイドを見る',
    trekListTitle: 'トレック一覧',
    trekListSubtitle: '地域・難易度・価格で検索。',
    trekSearch: '検索',
    trekRegion: 'すべての地域',
    trekDifficulty: '難易度',
    trekSeason: '最適シーズン',
    trekDuration: '期間',
    trekPrice: '価格',
    trekApply: '適用',
    trekViewDetails: '詳細',
    loginTitle: 'お帰りなさい',
    loginSubtitle: '予約管理のためログイン。',
    loginEmail: 'メール',
    loginPassword: 'パスワード',
    loginButton: 'ログイン',
    registerTitle: 'アカウント作成',
    registerSubtitle: '次の遠征を計画。',
    registerName: '氏名',
    registerEmail: 'メール',
    registerPassword: 'パスワード',
    registerConfirm: '確認',
    registerButton: '登録',
    myBookingsTitle: '予約',
    myBookingsSubtitle: '支払い状況と出発日。',
    payNow: '支払う',
    paymentTitle: '支払い',
    paymentSubtitle: '支払いで予約確定。',
    paymentDetails: '支払い詳細',
    paymentSuccessTitle: '支払い完了',
    paymentCancelTitle: '支払い取消',
    paymentGoBookings: '予約へ',
    paymentTryAgain: '再試行',
    aboutTitle: '私たちについて',
    blogTitle: 'トレイルジャーナル',
    contactTitle: 'お問い合わせ',
    faqTitle: 'よくある質問',
    guideTitle: '準備ガイド',
    partnersTitle: 'パートナー',
    trustTitle: '信頼と安全',
    calculatorTitle: '費用計算',
  },
  ko: {
    navHome: '홈',
    navTreks: '트레킹',
    navAbout: '소개',
    navBlog: '블로그',
    navGallery: '갤러리',
    navGuide: '가이드',
    navContact: '연락처',
    navAdmin: '관리자',
    navDashboard: '대시보드',
    navBookings: '내 예약',
    homeTagline: '히말라야 모험',
    homeTitle: 'Everest Encounter Treks & Expedition',
    homeSubtitle: '네팔에서 다음 원정을 계획하세요.',
    homeBook: '트레킹 예약',
    homeView: '패키지 보기',
    homeModesTitle: '모험 모드',
    homeModesSubtitle: '산으로 가는 방법을 선택하세요.',
    homeSignatureTitle: '대표 트레킹',
    homeSignatureView: '전체 보기',
    homeServicesTitle: '원정 서비스',
    homeServicesSubtitle: '허가, 물류, 고도 계획.',
    homePrepTitle: '출발 전 준비',
    homePrepSubtitle: '피트니스와 안전 가이드.',
    homeOpenGuide: '가이드 열기',
    trekListTitle: '트레킹 목록',
    trekListSubtitle: '지역, 난이도, 가격으로 필터.',
    trekSearch: '검색',
    trekRegion: '전체 지역',
    trekDifficulty: '난이도',
    trekSeason: '최적 시즌',
    trekDuration: '기간',
    trekPrice: '가격',
    trekApply: '필터 적용',
    trekViewDetails: '상세 보기',
    loginTitle: '다시 오신 것을 환영합니다',
    loginSubtitle: '예약 관리를 위해 로그인.',
    loginEmail: '이메일',
    loginPassword: '비밀번호',
    loginButton: '로그인',
    registerTitle: '계정 만들기',
    registerSubtitle: '다음 원정을 계획하세요.',
    registerName: '이름',
    registerEmail: '이메일',
    registerPassword: '비밀번호',
    registerConfirm: '비밀번호 확인',
    registerButton: '등록',
    myBookingsTitle: '내 예약',
    myBookingsSubtitle: '결제 상태 및 출발 일정.',
    payNow: '지금 결제',
    paymentTitle: '결제',
    paymentSubtitle: '결제를 완료하여 예약 확정.',
    paymentDetails: '결제 상세',
    paymentSuccessTitle: '결제 성공',
    paymentCancelTitle: '결제 취소',
    paymentGoBookings: '예약으로 이동',
    paymentTryAgain: '다시 시도',
    aboutTitle: '소개',
    blogTitle: '트레일 저널',
    contactTitle: '문의',
    faqTitle: '자주 묻는 질문',
    guideTitle: '준비 가이드',
    partnersTitle: '파트너',
    trustTitle: '신뢰와 안전',
    calculatorTitle: '비용 계산기',
  },
  ur: {
    navHome: 'ہوم',
    navTreks: 'ٹریکس',
    navAbout: 'ہمارے بارے',
    navBlog: 'بلاگ',
    navGallery: 'گیلری',
    navGuide: 'گائیڈ',
    navContact: 'رابطہ',
    navAdmin: 'ایڈمن',
    navDashboard: 'ڈیش بورڈ',
    navBookings: 'میری بُکنگز',
    homeTagline: 'ہمالیائی مہمات',
    homeTitle: 'ایورسٹ انکاؤنٹر ٹریکس',
    homeSubtitle: 'نیپال میں اپنے اگلے سفر کی منصوبہ بندی کریں۔',
    homeBook: 'ٹریک بُک کریں',
    homeView: 'پیکیجز دیکھیں',
    homeModesTitle: 'مہم کے طریقے',
    homeModesSubtitle: 'پہاڑوں تک پہنچنے کا طریقہ منتخب کریں۔',
    homeSignatureTitle: 'مشہور ٹریکس',
    homeSignatureView: 'تمام ٹریکس',
    homeServicesTitle: 'دور دراز مہمات کی خدمات',
    homeServicesSubtitle: 'لاجسٹکس، پرمٹس، اور بلندی کی منصوبہ بندی۔',
    homePrepTitle: 'سفر سے پہلے تیاری',
    homePrepSubtitle: 'فٹنس، پرمٹس، اور حفاظت کی رہنمائی۔',
    homeOpenGuide: 'گائیڈ کھولیں',
    trekListTitle: 'ٹریک فہرست',
    trekListSubtitle: 'علاقہ، مشکل، اور قیمت کے مطابق فلٹر کریں۔',
    trekSearch: 'تلاش کریں',
    trekRegion: 'تمام علاقے',
    trekDifficulty: 'مشکل',
    trekSeason: 'بہترین موسم',
    trekDuration: 'مدت',
    trekPrice: 'قیمت',
    trekApply: 'فلٹر لگائیں',
    trekViewDetails: 'تفصیل دیکھیں',
    loginTitle: 'خوش آمدید',
    loginSubtitle: 'بُکنگ مینج کرنے کیلئے لاگ اِن کریں۔',
    loginEmail: 'ای میل',
    loginPassword: 'پاس ورڈ',
    loginButton: 'لاگ اِن',
    registerTitle: 'اکاؤنٹ بنائیں',
    registerSubtitle: 'اپنی اگلی مہم پلان کریں۔',
    registerName: 'پورا نام',
    registerEmail: 'ای میل',
    registerPassword: 'پاس ورڈ',
    registerConfirm: 'تصدیق',
    registerButton: 'رجسٹر',
    myBookingsTitle: 'میری بُکنگز',
    myBookingsSubtitle: 'ادائیگی کی حالت اور روانگی کی تاریخیں۔',
    payNow: 'اب ادائیگی کریں',
    paymentTitle: 'ادائیگی',
    paymentSubtitle: 'بُکنگ کی تصدیق کیلئے ادائیگی کریں۔',
    paymentDetails: 'ادائیگی کی تفصیل',
    paymentSuccessTitle: 'ادائیگی کامیاب',
    paymentCancelTitle: 'ادائیگی منسوخ',
    paymentGoBookings: 'میری بُکنگز',
    paymentTryAgain: 'دوبارہ کوشش',
    aboutTitle: 'ہمارے بارے',
    blogTitle: 'ٹریل جرنل',
    contactTitle: 'رابطہ کریں',
    faqTitle: 'عمومی سوالات',
    guideTitle: 'تیاری گائیڈ',
    partnersTitle: 'پارٹنرز',
    trustTitle: 'اعتماد اور حفاظت',
    calculatorTitle: 'خرچ کیلکولیٹر',
  },
}

const LanguageContext = createContext({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
})

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(
    localStorage.getItem('everest_lang') || 'en',
  )

  const value = useMemo(() => {
    const table = translations[language] || translations.en
    return {
      language,
      setLanguage: (next) => {
        localStorage.setItem('everest_lang', next)
        setLanguage(next)
      },
      t: (key) => table[key] || translations.en[key] || key,
    }
  }, [language])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
